version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=monitor_view
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminPostgres,2023
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin,2023
    ports:
      - 5433:80
